### ISSUE TITLE
Tree view is messed up

### ISSUE THREAD

**Issue by dangayle** [dangayle/hyperterminator-ui#1]
If you select a folder, open and close it, the stupid css cascade makes the text color of all the items turn into the background color.

**Comment by rpichioli** [comment]
Solved it in this moment! 
I'm sending a pull request between today and tomorrow.
I've changed the mouse cursor in tabs and it's panel, to "pointer" and "default".

**Comment by dangayle** [comment]
Thanks @rpichioli!

**Comment by rpichioli** [comment]
You're welcome @dangayle!
