### ISSUE TITLE
Scrollbars are yuck

### ISSUE THREAD

**Issue by dangayle** [dangayle/hyperterminator-ui#2]
The tree view scroll bars are yucky. Need to basically steal the styles from the default Atom theme.

**Comment by rpichioli** [comment]
It's an awesome theme @dangayle. 
I suggest you to change the scrollbars to something like we can see in "Atom Dark" or "One Dark" themes.

**Comment by dangayle** [comment]
Thanks! Yeah, I need to figure that out.

--Dan

**Comment by dangayle** [comment]
https://github.com/dangayle/hyperterminator-ui/pull/3#merged-event
