### ISSUE TITLE
Deprecated selector in `Hyperterminator-ui\index.less`

### ISSUE THREAD

**Issue by rpichioli** [dangayle/hyperterminator-ui#7]
In `Hyperterminator-ui\index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor[mini] .placeholder-text,
atom-text-editor[mini]::shadow .placeholder-text` => `atom-text-editor[mini] .placeholder-text,
atom-text-editor[mini].editor .placeholder-text`

* `atom-text-editor[mini] .selection .region,
atom-text-editor[mini]::shadow .selection .region` => `atom-text-editor[mini] .selection .region,
atom-text-editor[mini].editor .selection .region`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by dangayle** [comment]
```prepend all your syntax selectors with syntax--```

What does that mean, exactly?

**Comment by rpichioli** [comment]
I'll take a look at that @dangayle! I've launched it automatically from the Atom deprecation warning, looks like a simple detail about commands that must be replaced, but it works anyway.

**Comment by dangayle** [comment]
Closed with https://github.com/dangayle/hyperterminator-ui/commit/bd3a1a59e5389eca0dc2a6a1d1c7dc70e70f5512
